# Generated by Django 5.1.1 on 2025-01-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('customer_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('company', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('phone_no1', models.CharField(max_length=20)),
                ('phone_no2', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('subscription_date', models.DateField()),
                ('website', models.URLField(max_length=100)),
            ],
        ),
    ]
