# Generated by Django 5.1.1 on 2025-01-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
