# Generated by Django 5.1.1 on 2025-01-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0003_remove_customermodel_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='index',
            field=models.IntegerField(default=1),
        ),
    ]
