# Generated by Django 5.1.1 on 2025-01-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0005_remove_customermodel_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
