# Generated by Django 5.1.1 on 2025-01-20 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0006_customermodel_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='index',
        ),
    ]
