# Generated by Django 5.1.1 on 2025-01-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0007_remove_customermodel_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='customer_id',
            field=models.CharField(max_length=100),
        ),
    ]
