# Generated by Django 5.1.1 on 2025-01-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0008_customermodel_id_alter_customermodel_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='customer_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
