# Generated by Django 5.1.1 on 2025-01-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0009_remove_customermodel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
