# Generated by Django 5.1.1 on 2025-01-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0010_customermodel_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='city',
            field=models.CharField(max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='company',
            field=models.CharField(max_length=50, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='customer_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Customer Id'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='first_name',
            field=models.CharField(max_length=25, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='index',
            field=models.IntegerField(default=0, verbose_name='Index'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='last_name',
            field=models.CharField(max_length=25, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='phone_no1',
            field=models.CharField(max_length=20, verbose_name='Phone 1'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='phone_no2',
            field=models.CharField(max_length=20, verbose_name='Phone 2'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='subscription_date',
            field=models.DateField(blank=True, null=True, verbose_name='Subscription Date'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='website',
            field=models.URLField(max_length=100, verbose_name='Website'),
        ),
    ]
