# Generated by Django 5.1.1 on 2025-01-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0011_alter_customermodel_city_alter_customermodel_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='subscription_date',
            field=models.DateField(verbose_name='Subscription Date'),
        ),
    ]
