# Generated by Django 5.1.1 on 2025-01-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0012_alter_customermodel_subscription_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='subscription_date',
            field=models.DateField(null=True, verbose_name='Subscription Date'),
        ),
    ]
