# Generated by Django 5.1.1 on 2025-01-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0013_alter_customermodel_subscription_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='company',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='customer_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='first_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='last_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='phone_no1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='phone_no2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='subscription_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='website',
            field=models.URLField(max_length=100),
        ),
    ]
