# Generated by Django 5.1.1 on 2025-01-28 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0014_alter_customermodel_city_alter_customermodel_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='last_name',
        ),
    ]
