# Generated by Django 5.1.1 on 2025-01-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0015_remove_customermodel_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='last_name',
            field=models.CharField(default='none', max_length=25),
        ),
    ]
